/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
        "on-secondary-fixed-variant": "#793100",
        "on-surface-variant": "#46474a",
        "primary": "#000000",
        "secondary": "#9f4200",
        "error": "#ba1a1a",
        "inverse-on-surface": "#f1f1f1",
        "on-surface": "#1a1c1c",
        "on-tertiary-container": "#848484",
        "surface-variant": "#e2e2e2",
        "surface-container-lowest": "#ffffff",
        "surface-container": "#eeeeee",
        "on-secondary-container": "#602500",
        "primary-fixed-dim": "#c8c6c7",
        "surface-container-highest": "#e2e2e2",
        "inverse-surface": "#2f3131",
        "on-error-container": "#93000a",
        "tertiary-fixed-dim": "#c7c6c6",
        "primary-fixed": "#e5e2e3",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed": "#1b1c1c",
        "secondary-container": "#ff7a2b",
        "tertiary-fixed": "#e3e2e2",
        "primary-container": "#1b1b1c",
        "on-error": "#ffffff",
        "surface-bright": "#f9f9f9",
        "on-tertiary-fixed-variant": "#464747",
        "on-background": "#1a1c1c",
        "background": "#f9f9f9",
        "surface-tint": "#5f5e5f",
        "on-primary-fixed": "#1b1b1c",
        "outline-variant": "#c7c6ca",
        "error-container": "#ffdad6",
        "secondary-fixed": "#ffdbcb",
        "on-primary-fixed-variant": "#474647",
        "inverse-primary": "#c8c6c7",
        "on-secondary-fixed": "#341100",
        "surface-dim": "#dadada",
        "surface-container-low": "#f3f3f3",
        "surface": "#f9f9f9",
        "on-primary-container": "#858384",
        "on-secondary": "#ffffff",
        "secondary-fixed-dim": "#ffb692",
        "tertiary": "#000000",
        "outline": "#76777b",
        "on-primary": "#ffffff",
        "tertiary-container": "#1b1c1c",
        "surface-container-high": "#e8e8e8"
      },
      "borderRadius": {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      "spacing": {
        "gutter": "24px",
        "base": "8px",
        "xl": "80px",
        "md": "24px",
        "margin-mobile": "16px",
        "margin-desktop": "64px",
        "lg": "48px",
        "xs": "4px",
        "sm": "12px"
      },
      "fontFamily": {
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-xl": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "label-sm": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "label-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg-mobile": ["Plus Jakarta Sans", "sans-serif"]
      },
      "fontSize": {
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "headline-xl": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "800" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "700" }],
        "label-sm": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "700" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "label-md": ["14px", { "lineHeight": "20px", "letterSpacing": "0.02em", "fontWeight": "600" }],
        "headline-lg-mobile": ["28px", { "lineHeight": "36px", "fontWeight": "700" }]
      }
    },
  },
  plugins: [],
}
